---
abstract: 'A one shot non-blocking RFC 812 WHOIS query.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-Whois
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Carp: 0
  Net::Netmask: 1.9012
  POE: 0.38
  POE::Filter::Line: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.18
