# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-Whois
version:      1.05
version_from: lib/POE/Component/Client/Whois.pm
installdirs:  site
requires:
    Carp:                          0
    Net::Netmask:                  1.9012
    POE:                           0.3202
    Socket:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
