---
abstract: 'A one shot non-blocking RFC 812 WHOIS query.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-Whois
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Client::Whois:
    file: lib/POE/Component/Client/Whois.pm
    version: 1.24
  POE::Component::Client::Whois::IPBlks:
    file: lib/POE/Component/Client/Whois/IPBlks.pm
    version: 1.24
  POE::Component::Client::Whois::TLDList:
    file: lib/POE/Component/Client/Whois/TLDList.pm
    version: 1.24
requires:
  Carp: 0
  Net::Netmask: 1.9012
  POE: 1.004
  POE::Filter::Line: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-client-whois/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-client-whois.git
version: 1.24
